version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: syncra-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: syncra_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"  

  redis:
    image: redis:7-alpine
    container_name: syncra-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
