using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Syncra.Application.DTOs.AI;
using Syncra.Application.Interfaces;
using Syncra.Application.Options;

namespace Syncra.Infrastructure.Services;

public sealed class GroqIdeaGenerationService : IAiIdeaGenerationService
{
    private static readonly string[] AllowedRepurposeTypes = ["POST", "THREAD", "CAROUSEL", "INSIGHT", "TIP", "QUOTE"];
    private static readonly string[] AllowedRepurposePlatforms = ["LinkedIn", "X", "Instagram", "Newsletter"];

    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        PropertyNameCaseInsensitive = true
    };

    private readonly HttpClient _httpClient;
    private readonly GroqOptions _options;
    private readonly ILogger<GroqIdeaGenerationService> _logger;

    public GroqIdeaGenerationService(
        HttpClient httpClient,
        IOptions<GroqOptions> options,
        ILogger<GroqIdeaGenerationService> logger)
    {
        _httpClient = httpClient;
        _options = options.Value;
        _logger = logger;
    }

    public async Task<GenerateIdeasResponseDto> GenerateIdeasAsync(
        Guid workspaceId,
        Guid userId,
        GenerateIdeasRequestDto request,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.Topic))
        {
            throw new ArgumentException("Topic is required.", nameof(request));
        }

        if (string.IsNullOrWhiteSpace(_options.ApiKey))
        {
            throw new InvalidOperationException("Groq API key is not configured. Set Groq__ApiKey in your environment.");
        }

        var count = Math.Clamp(request.Count <= 0 ? 5 : request.Count, 1, 10);

        var completion = await SendGroqJsonAsync(
            BuildIdeaSystemPrompt(),
            BuildIdeaUserPrompt(request, count),
            cancellationToken);

        var content = completion?.Choices?.FirstOrDefault()?.Message?.Content;
        if (string.IsNullOrWhiteSpace(content))
        {
            throw new InvalidOperationException("Groq returned empty content.");
        }

        var json = ExtractJson(content);
        var parsed = JsonSerializer.Deserialize<IdeasEnvelope>(json, JsonOptions);
        var normalized = NormalizeIdeas(parsed?.Ideas, count);

        if (normalized.Count == 0)
        {
            throw new InvalidOperationException("No valid ideas generated by Groq.");
        }

        return new GenerateIdeasResponseDto(request.Topic.Trim(), normalized);
    }

    public async Task<GenerateRepurposeResponseDto> GenerateRepurposeAsync(
        Guid workspaceId,
        Guid userId,
        GenerateRepurposeRequestDto request,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.SourceText))
        {
            throw new ArgumentException("SourceText is required.", nameof(request));
        }

        if (request.Platforms is null || request.Platforms.Count == 0)
        {
            throw new ArgumentException("At least one target platform is required.", nameof(request));
        }

        if (string.IsNullOrWhiteSpace(_options.ApiKey))
        {
            throw new InvalidOperationException("Groq API key is not configured. Set Groq__ApiKey in your environment.");
        }

        var completion = await SendGroqJsonAsync(
            BuildRepurposeSystemPrompt(),
            BuildRepurposeUserPrompt(request),
            cancellationToken);

        var content = completion?.Choices?.FirstOrDefault()?.Message?.Content;
        if (string.IsNullOrWhiteSpace(content))
        {
            throw new InvalidOperationException("Groq returned empty content for repurpose.");
        }

        var json = ExtractJson(content);
        var parsed = JsonSerializer.Deserialize<RepurposeEnvelope>(json, JsonOptions);
        var atoms = NormalizeRepurposeAtoms(parsed?.Atoms, request.Platforms, request.ExtractAtoms);

        if (atoms.Count == 0)
        {
            throw new InvalidOperationException("No valid repurpose outputs were generated by Groq.");
        }

        return new GenerateRepurposeResponseDto(atoms);
    }

    private async Task<GroqChatCompletionResponse?> SendGroqJsonAsync(
        string systemPrompt,
        string userPrompt,
        CancellationToken cancellationToken)
    {
        var candidateModels = new[] { _options.Model }
            .Concat(_options.FallbackModels ?? [])
            .Where(m => !string.IsNullOrWhiteSpace(m))
            .Select(m => m.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (candidateModels.Count == 0)
        {
            throw new InvalidOperationException("No Groq model configured.");
        }

        Exception? lastException = null;

        foreach (var model in candidateModels)
        {
            var payload = new
            {
                model,
                temperature = _options.Temperature,
                max_completion_tokens = _options.MaxCompletionTokens,
                messages = new object[]
                {
                    new
                    {
                        role = "system",
                        content = systemPrompt
                    },
                    new
                    {
                        role = "user",
                        content = userPrompt
                    }
                }
            };

            var req = new HttpRequestMessage(HttpMethod.Post, "/openai/v1/chat/completions")
            {
                Content = new StringContent(JsonSerializer.Serialize(payload), Encoding.UTF8, "application/json")
            };
            req.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _options.ApiKey);

            using var res = await _httpClient.SendAsync(req, cancellationToken);
            var body = await res.Content.ReadAsStringAsync(cancellationToken);

            if (res.IsSuccessStatusCode)
            {
                _logger.LogInformation("Groq request succeeded with model {Model}", model);
                return JsonSerializer.Deserialize<GroqChatCompletionResponse>(body, JsonOptions);
            }

            lastException = new HttpRequestException($"Groq API error ({model}): {(int)res.StatusCode}");
            _logger.LogWarning(
                "Groq API failed for model {Model} with status {StatusCode}: {Body}",
                model,
                (int)res.StatusCode,
                body);
        }

        throw lastException ?? new HttpRequestException("Groq API error: all candidate models failed.");
    }

    private static string BuildIdeaSystemPrompt() =>
        """
        You are Syncra AI, an expert social media strategist for content creators and small teams.

        Objective:
        Generate practical, ready-to-use content ideas that can be added directly into a planning board.
        Ideas must prioritize execution quality, audience relevance, and cross-platform adaptability.

        Output rules:
        - Return ONLY valid JSON (no markdown, no explanation).
        - JSON shape MUST be:
          {
            "ideas": [
              {
                "type": "Reel|Carousel|Photo|Thread|Short",
                "hook": "string",
                "title": "string",
                "caption": "string",
                "hashtags": ["#tag1", "#tag2"],
                "platforms": ["TikTok", "Instagram", "YouTube", "X", "LinkedIn", "Facebook"],
                "bestTime": "string",
                "estimatedReach": "string"
              }
            ]
          }
        - Keep captions concise, high-converting, and native to social media.
        - Include 4-8 relevant hashtags per idea, each hashtag must start with '#'.
        - Use mixed Vietnamese + English style only if it feels natural for creator content in Vietnam.
        - Ensure diversity of formats and angles (education, storytelling, authority, conversion).
        """;

    private static string BuildIdeaUserPrompt(GenerateIdeasRequestDto request, int count)
    {
        var fileContext = request.Files is { Count: > 0 }
            ? string.Join("\n", request.Files.Select(f =>
                $"- File: {f.Name} | Type: {f.Type} | Note: {f.Caption ?? "(none)"}"))
            : "- No reference files provided.";

        return $"""
        Generate exactly {count} social content ideas for Syncra users.

        Constraints:
        - Topic: {request.Topic}
        - Niche: {request.Niche ?? "General"}
        - Audience: {request.Audience ?? "General audience"}
        - Goal: {request.Goal ?? "engagement"}
        - Tone: {request.Tone ?? "balanced"}

        Reference context:
        {fileContext}

        Return only JSON in the required schema.
        """;
    }

        private static string BuildRepurposeSystemPrompt() =>
                """
                You are Syncra AI Repurpose Engine.

                Mission:
                Convert one long-form source content into platform-ready short-form outputs.

                Output format:
                Return ONLY valid JSON with shape:
                {
                    "atoms": [
                        {
                            "type": "POST|THREAD|CAROUSEL|INSIGHT|TIP|QUOTE",
                            "title": "string or null",
                            "content": "string",
                            "platform": "LinkedIn|X|Instagram|Newsletter",
                            "suggestedHashtags": ["#tag1", "#tag2"],
                            "suggestedCta": "string or null"
                        }
                    ]
                }

                Quality rules:
                - Keep outputs actionable and specific to creator workflows.
                - Adapt tone and formatting per platform conventions.
                - Hashtags must start with '#', max 6.
                - Never output markdown fences.
                """;

        private static string BuildRepurposeUserPrompt(GenerateRepurposeRequestDto request)
        {
                var platforms = string.Join(", ", request.Platforms);
                var mode = request.ExtractAtoms
                        ? "INSIGHTS MODE: prioritize atomized nuggets (INSIGHT/TIP/QUOTE)."
                        : "FULL MODE: mix long output formats (POST/THREAD/CAROUSEL) with concise atoms.";

                return $"""
                Repurpose this source content for Syncra users.

                Constraints:
                - Platforms: {platforms}
                - Tone: {request.Tone ?? "adaptive"}
                - Length: {request.Length ?? "medium"}
                - {mode}

                Source content:
                {request.SourceText}

                Return strict JSON only.
                """;
        }

    private static string ExtractJson(string raw)
    {
        var trimmed = raw.Trim();

        if (trimmed.StartsWith("```") && trimmed.Contains('\n'))
        {
            var firstNewline = trimmed.IndexOf('\n');
            trimmed = trimmed[(firstNewline + 1)..];
            var closingFence = trimmed.LastIndexOf("```");
            if (closingFence >= 0)
            {
                trimmed = trimmed[..closingFence];
            }
        }

        var start = trimmed.IndexOf('{');
        var end = trimmed.LastIndexOf('}');
        if (start >= 0 && end > start)
        {
            return trimmed[start..(end + 1)];
        }

        return trimmed;
    }

    private static IReadOnlyCollection<GeneratedIdeaDto> NormalizeIdeas(IReadOnlyCollection<RawIdea>? ideas, int count)
    {
        if (ideas is null || ideas.Count == 0)
        {
            return Array.Empty<GeneratedIdeaDto>();
        }

        var normalized = ideas
            .Where(i => !string.IsNullOrWhiteSpace(i.Title) && !string.IsNullOrWhiteSpace(i.Hook) && !string.IsNullOrWhiteSpace(i.Caption))
            .Take(count)
            .Select((idea, idx) => new GeneratedIdeaDto(
                Id: $"ai-{DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()}-{idx + 1}",
                Type: NormalizeType(idea.Type),
                Hook: idea.Hook!.Trim(),
                Title: idea.Title!.Trim(),
                Caption: idea.Caption!.Trim(),
                Hashtags: NormalizeHashtags(idea.Hashtags),
                Platforms: NormalizePlatforms(idea.Platforms),
                BestTime: string.IsNullOrWhiteSpace(idea.BestTime) ? "19:00 - 21:00" : idea.BestTime.Trim(),
                EstimatedReach: string.IsNullOrWhiteSpace(idea.EstimatedReach) ? "5K - 20K" : idea.EstimatedReach.Trim()
            ))
            .ToList();

        return normalized;
    }

    private static string NormalizeType(string? type)
    {
        if (string.IsNullOrWhiteSpace(type)) return "Reel";
        var val = type.Trim().ToLowerInvariant();

        return val switch
        {
            "reel" => "Reel",
            "carousel" => "Carousel",
            "photo" => "Photo",
            "thread" => "Thread",
            "short" => "Short",
            _ => "Reel"
        };
    }

    private static IReadOnlyCollection<string> NormalizeHashtags(IReadOnlyCollection<string>? hashtags)
    {
        if (hashtags is null || hashtags.Count == 0)
        {
            return new[] { "#contentcreator", "#socialmedia", "#syncra" };
        }

        return hashtags
            .Select(h => h?.Trim() ?? string.Empty)
            .Where(h => !string.IsNullOrWhiteSpace(h))
            .Select(h => h.StartsWith('#') ? h : $"#{h}")
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Take(8)
            .ToList();
    }

    private static IReadOnlyCollection<string> NormalizePlatforms(IReadOnlyCollection<string>? platforms)
    {
        if (platforms is null || platforms.Count == 0)
        {
            return new[] { "TikTok", "Instagram" };
        }

        return platforms
            .Select(p => p?.Trim())
            .Where(p => !string.IsNullOrWhiteSpace(p))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Take(4)
            .ToList()!;
    }

    private static IReadOnlyCollection<RepurposeAtomDto> NormalizeRepurposeAtoms(
        IReadOnlyCollection<RawRepurposeAtom>? atoms,
        IReadOnlyCollection<string> requestedPlatforms,
        bool extractAtoms)
    {
        if (atoms is null || atoms.Count == 0)
        {
            return Array.Empty<RepurposeAtomDto>();
        }

        var requested = requestedPlatforms
            .Select(NormalizeRepurposePlatform)
            .Where(p => !string.IsNullOrWhiteSpace(p))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        var filtered = atoms
            .Where(a => !string.IsNullOrWhiteSpace(a.Content))
            .Select((a, idx) =>
            {
                var normalizedType = NormalizeRepurposeType(a.Type, extractAtoms);
                var platform = NormalizeRepurposePlatform(a.Platform);
                if (string.IsNullOrWhiteSpace(platform) || !requested.Contains(platform))
                {
                    platform = requested.FirstOrDefault() ?? "LinkedIn";
                }

                return new RepurposeAtomDto(
                    Id: $"rep-{DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()}-{idx + 1}",
                    Type: normalizedType,
                    Title: string.IsNullOrWhiteSpace(a.Title) ? null : a.Title.Trim(),
                    Content: a.Content!.Trim(),
                    Platform: platform,
                    SuggestedHashtags: NormalizeHashtags(a.SuggestedHashtags).Take(6).ToList(),
                    SuggestedCta: string.IsNullOrWhiteSpace(a.SuggestedCta) ? null : a.SuggestedCta.Trim()
                );
            })
            .ToList();

        if (extractAtoms)
        {
            var atomTypes = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "INSIGHT", "TIP", "QUOTE" };
            filtered = filtered.Where(f => atomTypes.Contains(f.Type)).ToList();
        }

        return filtered.Take(20).ToList();
    }

    private static string NormalizeRepurposePlatform(string? platform)
    {
        if (string.IsNullOrWhiteSpace(platform)) return string.Empty;
        var val = platform.Trim().ToLowerInvariant();

        return val switch
        {
            "linkedin" => "LinkedIn",
            "x" => "X",
            "twitter" => "X",
            "instagram" => "Instagram",
            "newsletter" => "Newsletter",
            _ => AllowedRepurposePlatforms.FirstOrDefault(p => p.Equals(platform.Trim(), StringComparison.OrdinalIgnoreCase)) ?? string.Empty
        };
    }

    private static string NormalizeRepurposeType(string? type, bool extractAtoms)
    {
        if (string.IsNullOrWhiteSpace(type))
        {
            return extractAtoms ? "INSIGHT" : "POST";
        }

        var upper = type.Trim().ToUpperInvariant();
        if (AllowedRepurposeTypes.Contains(upper, StringComparer.OrdinalIgnoreCase))
        {
            return upper;
        }

        return extractAtoms ? "INSIGHT" : "POST";
    }

    private sealed record GroqChatCompletionResponse(IReadOnlyCollection<GroqChoice>? Choices);
    private sealed record GroqChoice(GroqMessage? Message);
    private sealed record GroqMessage(string? Content);

    private sealed record IdeasEnvelope(IReadOnlyCollection<RawIdea>? Ideas);
    private sealed record RepurposeEnvelope(IReadOnlyCollection<RawRepurposeAtom>? Atoms);

    private sealed record RawIdea(
        string? Type,
        string? Hook,
        string? Title,
        string? Caption,
        IReadOnlyCollection<string>? Hashtags,
        IReadOnlyCollection<string>? Platforms,
        string? BestTime,
        string? EstimatedReach
    );

    private sealed record RawRepurposeAtom(
        string? Type,
        string? Title,
        string? Content,
        string? Platform,
        IReadOnlyCollection<string>? SuggestedHashtags,
        string? SuggestedCta
    );
}
