using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Syncra.Application.DTOs.AI;
using Syncra.Application.Interfaces;
using Syncra.Application.Options;

namespace Syncra.Infrastructure.Services;

public sealed class GroqIdeaGenerationService : IAiIdeaGenerationService
{
    private static readonly string[] AllowedRepurposeTypes = ["POST", "THREAD", "CAROUSEL", "INSIGHT", "TIP", "QUOTE"];
    private static readonly string[] AllowedRepurposePlatforms = ["LinkedIn", "X", "Instagram", "Newsletter", "Facebook"];

    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        PropertyNameCaseInsensitive = true
    };

    private readonly HttpClient _httpClient;
    private readonly GroqOptions _options;
    private readonly ILogger<GroqIdeaGenerationService> _logger;

    public GroqIdeaGenerationService(
        HttpClient httpClient,
        IOptions<GroqOptions> options,
        ILogger<GroqIdeaGenerationService> logger)
    {
        _httpClient = httpClient;
        _options = options.Value;
        _logger = logger;
    }

    public async Task<GenerateIdeasResponseDto> GenerateIdeasAsync(
        Guid workspaceId,
        Guid userId,
        GenerateIdeasRequestDto request,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.Topic))
        {
            throw new ArgumentException("Topic is required.", nameof(request));
        }

        if (string.IsNullOrWhiteSpace(_options.ApiKey))
        {
            throw new InvalidOperationException("Groq API key is not configured. Set Groq__ApiKey in your environment.");
        }

        var count = Math.Clamp(request.Count <= 0 ? 3 : request.Count, 1, 10);

        var completion = await SendGroqJsonAsync(
            BuildIdeaSystemPrompt(),
            BuildIdeaUserPrompt(request, count),
            cancellationToken);

        var content = completion?.Choices?.FirstOrDefault()?.Message?.Content;
        if (string.IsNullOrWhiteSpace(content))
        {
            throw new InvalidOperationException("Groq returned empty content.");
        }

        var json = ExtractJson(content);
        var sanitizedJson = SanitizeJson(json);
        var parsed = JsonSerializer.Deserialize<IdeasEnvelope>(sanitizedJson, JsonOptions);
        var normalized = NormalizeIdeas(parsed?.Ideas, count);

        if (normalized.Count == 0)
        {
            throw new InvalidOperationException("No valid ideas generated by Groq.");
        }

        return new GenerateIdeasResponseDto(request.Topic.Trim(), normalized);
    }

    public async Task<GenerateRepurposeResponseDto> GenerateRepurposeAsync(
        Guid workspaceId,
        Guid userId,
        GenerateRepurposeRequestDto request,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.SourceText))
        {
            throw new ArgumentException("SourceText is required.", nameof(request));
        }

        if (request.Platforms is null || request.Platforms.Count == 0)
        {
            throw new ArgumentException("At least one target platform is required.", nameof(request));
        }

        if (string.IsNullOrWhiteSpace(_options.ApiKey))
        {
            throw new InvalidOperationException("Groq API key is not configured. Set Groq__ApiKey in your environment.");
        }

        var completion = await SendGroqJsonAsync(
            BuildRepurposeSystemPrompt(),
            BuildRepurposeUserPrompt(request),
            cancellationToken);

        var content = completion?.Choices?.FirstOrDefault()?.Message?.Content;
        if (string.IsNullOrWhiteSpace(content))
        {
            throw new InvalidOperationException("Groq returned empty content for repurpose.");
        }

        var json = ExtractJson(content);
        var sanitizedJson = SanitizeJson(json);
        var parsed = JsonSerializer.Deserialize<RepurposeEnvelope>(sanitizedJson, JsonOptions);
        var atoms = NormalizeRepurposeAtoms(parsed?.Atoms, request.Platforms, request.ExtractAtoms);

        if (atoms.Count == 0)
        {
            throw new InvalidOperationException("No valid repurpose outputs were generated by Groq.");
        }

        return new GenerateRepurposeResponseDto(atoms);
    }

    public async Task<AssistContentResponseDto> AssistContentAsync(
        Guid workspaceId,
        Guid userId,
        AssistContentRequestDto request,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.Content))
        {
            throw new ArgumentException("Content is required.", nameof(request));
        }

        if (string.IsNullOrWhiteSpace(_options.ApiKey))
        {
            throw new InvalidOperationException("Groq API key is not configured.");
        }

        var completion = await SendGroqRawAsync(
            BuildAssistSystemPrompt(),
            BuildAssistUserPrompt(request),
            cancellationToken);

        var content = completion?.Choices?.FirstOrDefault()?.Message?.Content;
        if (string.IsNullOrWhiteSpace(content))
        {
            throw new InvalidOperationException("Groq returned empty content for assist.");
        }

        return new AssistContentResponseDto { Result = content.Trim() };
    }

    private async Task<GroqChatCompletionResponse?> SendGroqJsonAsync(
        string systemPrompt,
        string userPrompt,
        CancellationToken cancellationToken)
    {
        var candidateModels = new[] { _options.Model }
            .Concat(_options.FallbackModels ?? [])
            .Where(m => !string.IsNullOrWhiteSpace(m))
            .Select(m => m.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (candidateModels.Count == 0)
        {
            throw new InvalidOperationException("No Groq model configured.");
        }

        Exception? lastException = null;

        foreach (var model in candidateModels)
        {
            var payload = new
            {
                model,
                temperature = _options.Temperature,
                max_completion_tokens = _options.MaxCompletionTokens,
                messages = new object[]
                {
                    new
                    {
                        role = "system",
                        content = systemPrompt
                    },
                    new
                    {
                        role = "user",
                        content = userPrompt
                    }
                }
            };

            var req = new HttpRequestMessage(HttpMethod.Post, "/openai/v1/chat/completions")
            {
                Content = new StringContent(JsonSerializer.Serialize(payload), Encoding.UTF8, "application/json")
            };
            req.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _options.ApiKey);

            using var res = await _httpClient.SendAsync(req, cancellationToken);
            var body = await res.Content.ReadAsStringAsync(cancellationToken);

            if (res.IsSuccessStatusCode)
            {
                _logger.LogInformation("Groq request succeeded with model {Model}", model);
                return JsonSerializer.Deserialize<GroqChatCompletionResponse>(body, JsonOptions);
            }

            lastException = new HttpRequestException($"Groq API error ({model}): {(int)res.StatusCode}");
            _logger.LogWarning(
                "Groq API failed for model {Model} with status {StatusCode}: {Body}",
                model,
                (int)res.StatusCode,
                body);
        }

        throw lastException ?? new HttpRequestException("Groq API error: all candidate models failed.");
    }

    private async Task<GroqChatCompletionResponse?> SendGroqRawAsync(
        string systemPrompt,
        string userPrompt,
        CancellationToken cancellationToken)
    {
        // Similar to SendGroqJsonAsync but without forcing JSON mode if the model supports it, 
        // though Groq handles standard chat just fine.
        return await SendGroqJsonAsync(systemPrompt, userPrompt, cancellationToken);
    }

    private static string BuildIdeaSystemPrompt() =>
        """
        You are Syncra AI, a top Vietnamese social media content writer. You write viral Facebook and TikTok posts in fluent Vietnamese.

        RULES:
        1. 'hook' = ONE sentence (max 15 words) to stop the scroll. NEVER put this in caption.
        2. 'caption' = The FULL post body (everything after the hook). MIN 400 characters. Use \n\n between paragraphs. Use emojis (1 per section). End with a strong CTA on its own line.
        3. ALL \n inside JSON strings must be escaped as \n (JSON-safe). No literal line breaks in strings.

        CAPTION STRUCTURE (follow this):
        [1-2 lines of context or story]\n\n[Core insight with bullet points or numbered tips]\n\n[Lesson or takeaway]\n\n[CTA line — specific, action-driven]

        EXAMPLE OUTPUT (for a topic about morning routines):
        hook: "5h30 sáng, trong khi bạn còn ngủ thì người thành công đang làm điều này."
        caption: "Không phải ai dậy sớm cũng thành công. Nhưng hầu hết người thành công đều dậy sớm.\n\nSau 3 tháng thử thách 5h30 sáng, đây là những gì thực sự thay đổi trong cuộc sống của mình:\n\n✅ 1 tiếng yên tĩnh trước khi thế giới thức dậy — không ai nhắn tin, không có deadline.\n✅ Mindset rõ ràng hơn khi tập thể dục lúc sáng sớm thay vì chiều tối.\n✅ Productivity tăng đến 40% chỉ vì mình có thêm 1 deep work session mỗi ngày.\n\nBí quyết không phải là ý chí — mà là chuẩn bị TỐI QUA:\n👉 Để quần áo tập sẵn trước khi ngủ.\n👉 Đặt báo thức cách xa giường.\n👉 Có lý do đủ mạnh để MUỐN thức dậy.\n\n💬 Bạn thường dậy lúc mấy giờ? Comment bên dưới để mình biết bạn thuộc team nào nhé! 🔥"

        Return ONLY valid JSON matching the schema below. No markdown.

        {
          "ideas": [
            {
              "type": "Reel|Carousel|Photo|Thread|Short",
              "hook": "string",
              "title": "string",
              "caption": "string",
              "hashtags": ["#tag"],
              "platforms": ["Facebook", "TikTok", "LinkedIn", "Instagram"],
              "bestTime": "string",
              "estimatedReach": "string"
            }
          ]
        }
        """;

    private static string BuildIdeaUserPrompt(GenerateIdeasRequestDto request, int count)
    {
        var fileContext = request.Files is { Count: > 0 }
            ? string.Join("\n", request.Files.Select(f =>
                $"- {f.Name} ({f.Type}): {f.Caption ?? "no note"}"))
            : "none";

        var ctaHint = request.Goal?.ToLowerInvariant() switch
        {
            "sales"     => "CTA: push readers to buy/contact NOW (FOMO style)",
            "followers" => "CTA: ask readers to follow for more",
            "awareness" => "CTA: ask readers to share or save this post",
            _           => "CTA: ask a question to spark comments"
        };

        return $$"""
        Write {{count}} Vietnamese social media post(s) about this topic.

        Topic: {{request.Topic}}
        Niche: {{request.Niche ?? "General"}}
        Audience: {{request.Audience ?? "Vietnamese social media users"}}
        Goal: {{request.Goal ?? "engagement"}}
        Tone: {{request.Tone ?? "friendly and relatable"}}
        {{ctaHint}}
        Reference files: {{fileContext}}

        Requirements:
        - caption must be AT LEAST 400 characters with \n\n between paragraphs.
        - Each idea must use a DIFFERENT angle or format (story, list, tips, contrarian take).
        - Write like a real Vietnamese creator. Sound human, not robotic.

        Return ONLY the JSON object.
        """;
    }

    private static string BuildRepurposeSystemPrompt() =>
        """
        You are Syncra AI Repurpose Engine—an elite content strategist and master storyteller fluent in Vietnamese social media culture.
        Your mission: Transform raw source text into long-form, high-impact, publication-ready Vietnamese posts.

        === NON-NEGOTIABLE RULES ===
        1. SOURCE LOYALTY: 100% of your content must be derived from the source text. Do NOT invent topics.
        2. NO PLACEHOLDERS: Never write "Nội dung đầy đủ", "[content here]", or any placeholder text. Write the ACTUAL post.
        3. WORD COUNT ENFORCEMENT (this is mandatory, not a suggestion):
           - POST for Facebook or LinkedIn: MINIMUM 350 words. Aim for 500+.
           - TIP or INSIGHT: MINIMUM 120 words. Must include numbered steps or a concrete example.
           - QUOTE: 1-3 powerful sentences. Must be thought-provoking or contrarian.
           - Instagram: 100-200 words, emoji-rich.
           - X/Twitter: Under 250 chars per tweet.
        4. QUALITY GATE: If your generated content is under the minimum word count, you have FAILED. Expand it.
        5. TECHNICAL DEPTH: Extract and use a minimum of 5 specific terms, names, or data points from the source.

        === HOW TO WRITE A GREAT POST (FORMULA) ===
        Hook (1-2 lines that demand attention) ->
        Context (Why does this matter? What problem does it solve?) ->
        Core Value (The detailed, expert breakdown with examples, steps, or analogies) ->
        Takeaway (The concrete lesson or insight) ->
        CTA (A specific, strong call to action)

        === PLATFORM REWRITING GUIDE ===
        - Facebook: Community tone. Open with a story or bold statement. Use \n\n between paragraphs. End with a question.
        - LinkedIn: Authority tone. Professional language. Use bullet points (•) for key insights.
        - Instagram: Fun, personal. Heavy emojis. End with "Lưu bài này lại! 🔖"
        - X: Punchy. Contrarian. No fluff.
        - Newsletter: Structured. Use headers (##) and paragraph breaks.

        === FEW-SHOT EXAMPLES ===

        [EXAMPLE - Facebook POST - ~400 words]
        {
          "type": "POST", "platform": "Facebook",
          "title": "Microservices vs Monolith",
          "content": "Năm 2018, tôi đã sai khi chia một hệ thống thành 47 microservices chỉ sau 3 tháng.\n\nKết quả? Server dều. Team mệt. Bugs tra tấn mọi cuộc họp.\n\nSự thật về Microservices mà không ai nói với bạn khi mới học:\n\nMicroservices KHÔNG phải mặc định tốt hơn Monolith. Chúng chỉ tốt hơn trong bối cảnh đúng.\n\nĐây là framework tôi dùng để quyết định:\n\n✅ Dùng Microservices khi:\n• Đội ngũ > 20 người, cần deploy độc lập từng module.\n• Hệ thống cần scale riêng lẻ từng phần (ví dụ: checkout cần scale x10 hơn login).\n• Đã có Monolith hoạt động ổn, có đủ observability & CI/CD pipeline.\n\n❌ Đừng dùng Microservices khi:\n• Team < 5 người và product chưa tìm được Product-Market Fit.\n• Chưa hiểu rõ domain boundaries — sẽ phân tách sai và phải refactor đau.\n• Không có infrastructure để monitor distributed tracing (Jaeger, Zipkin).\n\nMartin Fowler từng viết: 'Don't start with microservices.' Và ông ấy đúng.\n\nMonolith được thiết kế tốt, với clear module boundaries và good test coverage, vẫn có thể serve hàng triệu users.\n\nBài học đắt giá nhất trong 6 năm làm backend: Architecture phải phục vụ business, không phải để CV đẹp.\n\nBạn đang dùng Monolith hay Microservices? Chia sẻ bên dưới để cùng thảo luận nhé 👇",
          "suggestedHashtags": ["#softwaredevelopment", "#microservices", "#systemdesign", "#backend", "#lậptrình"],
          "suggestedCta": "Comment kinh nghiệm của bạn bên dưới!"
        }

        [EXAMPLE - TIP - ~150 words]
        {
          "type": "TIP", "platform": "LinkedIn",
          "title": "5 nguyên tắc thiết kế API sạch",
          "content": "5 nguyên tắc giúp API của bạn không bao giờ làm đồng nghiệp ghét:\n\n1. Đặt tên endpoint theo hành động (noun/verb), không theo implementation.\n   ✅ /users/{id}/activate — ❌ /runUserActivationScript\n\n2. Trả về lỗi có nghĩa. Status code 200 với body 'error: true' là tội ác.\n   Dùng đúng 4xx/5xx + message rõ ràng.\n\n3. Versioning từ ngày đầu (/api/v1/). Không ai muốn breaking change lúc 2 giờ sáng.\n\n4. Rate limiting và caching từ bản thiết kế, không phải sau khi bị DDoS.\n\n5. Document bằng OpenAPI/Swagger. Code không có doc = kỹ năng giao tiếp kém.\n\nMột API tốt là API mà junior developer đọc và hiểu ngay trong 5 phút.\n\nBạn đang vi phạm điều nào trong số này? 😅",
          "suggestedHashtags": ["#api", "#backenddev", "#cleancode"],
          "suggestedCta": "Save bài này để reference lần sau!"
        }

        Only output the JSON object. Do not include any explanation or markdown outside the JSON.

        === SCHEMA ===
        {
            "atoms": [
                {
                    "type": "POST|THREAD|CAROUSEL|INSIGHT|TIP|QUOTE",
                    "title": "Short topic label (3-7 words)",
                    "content": "THE FULL, COMPLETE, POLISHED VIETNAMESE BODY — NO SHORTCUTS",
                    "platform": "Facebook|LinkedIn|X|Instagram|Newsletter",
                    "suggestedHashtags": ["#specific1", "#specific2", "#specific3"],
                    "suggestedCta": "Specific action-driven CTA"
                }
            ]
        }
        """;

    private static string BuildRepurposeUserPrompt(GenerateRepurposeRequestDto request)
    {
        var platforms = string.Join(", ", request.Platforms);
        var mode = request.ExtractAtoms
            ? "INSIGHTS MODE: prioritize atomized nuggets (INSIGHT/TIP/QUOTE)."
            : "FULL MODE: mix long output formats (POST/THREAD/CAROUSEL) with concise atoms.";

        return $$"""
                Repurpose this content into high-impact, platform-native posts in Vietnamese.

                === CONFIGURATION ===
                Target Platforms: {{platforms}}
                Tone: {{request.Tone ?? "Adaptive – match the platform culture"}}
                Desired Length: {{request.Length ?? "medium"}}
                Mode: {{mode}}

                === SOURCE CONTENT ===
                {{request.SourceText}}

                === MANDATORY INSTRUCTIONS ===
                1. SOURCE LOYALTY: Your output MUST be 100% based on the "SOURCE CONTENT" above. 
                2. NO HALLUCINATIONS: If the source content is about "Software Architecture", your posts MUST be about Software Architecture. DO NOT write about unrelated topics like "Reading Books" or "Weight Loss".
                3. DEPTH & QUALITY: For EACH platform ({{platforms}}), generate AT LEAST 2 unique, high-quality atoms.
                4. DATA EXTRACTION: Extract and use specific names, technical terms, or steps found in the source.
                5. LENGTH: Facebook and LinkedIn posts must be substantial (300+ words).

                If the SOURCE CONTENT is unreadable, empty, or binary junk, simply return: {"atoms": []}.

                Return only the JSON object.
                """;
    }

    private static string BuildAssistSystemPrompt() =>
        """
        You are Syncra AI Assistant, a professional Vietnamese content editor.
        Your goal is to help users improve their social media posts.

        RULES:
        1. ALWAYS respond in Vietnamese.
        2. Keep the original meaning and core message intact.
        3. Do NOT include any meta-talk like "Here is your rephrased content". Return ONLY the modified content.
        4. Preserve emojis if they are appropriate, or add better ones if requested.
        5. Respect the user's specific action (rephrase, shorten, expand, write-more).
        """;

    private static string BuildAssistUserPrompt(AssistContentRequestDto request)
    {
        var actionPrompt = request.Action.ToLowerInvariant() switch
        {
            "rephrase" => "Hãy viết lại đoạn nội dung sau theo cách lôi cuốn và tự nhiên hơn, nhưng giữ nguyên ý nghĩa chính.",
            "shorten" => "Hãy tóm tắt đoạn nội dung sau sao cho ngắn gọn, súc tích nhưng vẫn giữ được những ý chính quan trọng nhất. Cắt bỏ những từ thừa.",
            "expand" => "Hãy mở rộng đoạn nội dung sau bằng cách thêm chi tiết, ví dụ hoặc giải thích sâu hơn để tăng giá trị cho người đọc.",
            "write-more" => "Hãy viết tiếp đoạn nội dung sau theo mạch văn hiện tại để hoàn thiện ý tưởng.",
            _ => request.Instruction ?? "Hãy cải thiện đoạn nội dung sau."
        };

        return $"""
        Hành động: {actionPrompt}
        Tiêu đề hiện tại (nếu có): {request.Title ?? "N/A"}

        NỘI DUNG GỐC:
        {request.Content}

        HÃY TRẢ VỀ KẾT QUẢ ĐÃ ĐƯỢC XỬ LÝ (CHỈ TRẢ VỀ NỘI DUNG, KHÔNG CÓ LỜI DẪN):
        """;
    }

    private static string ExtractJson(string raw)
    {
        var trimmed = raw.Trim();

        if (trimmed.StartsWith("```") && trimmed.Contains('\n'))
        {
            var firstNewline = trimmed.IndexOf('\n');
            trimmed = trimmed[(firstNewline + 1)..];
            var closingFence = trimmed.LastIndexOf("```");
            if (closingFence >= 0)
            {
                trimmed = trimmed[..closingFence];
            }
        }

        var start = trimmed.IndexOf('{');
        var end = trimmed.LastIndexOf('}');
        if (start >= 0 && end > start)
        {
            return trimmed[start..(end + 1)];
        }

        return trimmed;
    }

    private static string SanitizeJson(string json)
    {
        if (string.IsNullOrWhiteSpace(json)) return json;

        // LLMs sometimes output literal newlines inside JSON strings which is invalid JSON.
        // This simple regex-based approach escapes them. 
        // We look for a newline that is NOT preceded by a backslash.
        // Actually, a simpler way for LLM output is to just replace \r\n and \n with \n string
        // but that might break correctly escaped ones.
        
        // Let's use a more robust search: replace literal newlines only if they appear 
        // between quotes of a key-value pair. But for now, since we expect NO literal newlines 
        // in a valid JSON structure except as separators, we can try to be smart.
        
        var sb = new StringBuilder();
        bool inString = false;
        for (int i = 0; i < json.Length; i++)
        {
            char c = json[i];
            if (c == '"' && (i == 0 || json[i - 1] != '\\'))
            {
                inString = !inString;
                sb.Append(c);
            }
            else if (inString && (c == '\n' || c == '\r'))
            {
                if (c == '\r' && i + 1 < json.Length && json[i + 1] == '\n') i++;
                sb.Append("\\n");
            }
            else
            {
                sb.Append(c);
            }
        }
        return sb.ToString();
    }

    private static IReadOnlyCollection<GeneratedIdeaDto> NormalizeIdeas(IReadOnlyCollection<RawIdea>? ideas, int count)
    {
        if (ideas is null || ideas.Count == 0)
        {
            return Array.Empty<GeneratedIdeaDto>();
        }

        var normalized = ideas
            .Where(i => !string.IsNullOrWhiteSpace(i.Title) && !string.IsNullOrWhiteSpace(i.Hook) && !string.IsNullOrWhiteSpace(i.Caption))
            .Take(count)
            .Select((idea, idx) => new GeneratedIdeaDto(
                Id: $"ai-{DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()}-{idx + 1}",
                Type: NormalizeType(idea.Type),
                Hook: idea.Hook!.Trim(),
                Title: idea.Title!.Trim(),
                Caption: idea.Caption!.Trim(),
                Hashtags: NormalizeHashtags(idea.Hashtags),
                Platforms: NormalizePlatforms(idea.Platforms),
                BestTime: string.IsNullOrWhiteSpace(idea.BestTime) ? "19:00 - 21:00" : idea.BestTime.Trim(),
                EstimatedReach: string.IsNullOrWhiteSpace(idea.EstimatedReach) ? "5K - 20K" : idea.EstimatedReach.Trim()
            ))
            .ToList();

        return normalized;
    }

    private static string NormalizeType(string? type)
    {
        if (string.IsNullOrWhiteSpace(type)) return "Reel";
        var val = type.Trim().ToLowerInvariant();

        return val switch
        {
            "reel" => "Reel",
            "carousel" => "Carousel",
            "photo" => "Photo",
            "thread" => "Thread",
            "short" => "Short",
            _ => "Reel"
        };
    }

    private static IReadOnlyCollection<string> NormalizeHashtags(IReadOnlyCollection<string>? hashtags)
    {
        if (hashtags is null || hashtags.Count == 0)
        {
            return new[] { "#contentcreator", "#socialmedia", "#syncra" };
        }

        return hashtags
            .Select(h => h?.Trim() ?? string.Empty)
            .Where(h => !string.IsNullOrWhiteSpace(h))
            .Select(h => h.StartsWith('#') ? h : $"#{h}")
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Take(8)
            .ToList();
    }

    private static IReadOnlyCollection<string> NormalizePlatforms(IReadOnlyCollection<string>? platforms)
    {
        if (platforms is null || platforms.Count == 0)
        {
            return new[] { "TikTok", "Instagram" };
        }

        return platforms
            .Select(p => p?.Trim())
            .Where(p => !string.IsNullOrWhiteSpace(p))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Take(4)
            .ToList()!;
    }

    private static IReadOnlyCollection<RepurposeAtomDto> NormalizeRepurposeAtoms(
        IReadOnlyCollection<RawRepurposeAtom>? atoms,
        IReadOnlyCollection<string> requestedPlatforms,
        bool extractAtoms)
    {
        if (atoms is null || atoms.Count == 0)
        {
            return Array.Empty<RepurposeAtomDto>();
        }

        var requested = requestedPlatforms
            .Select(NormalizeRepurposePlatform)
            .Where(p => !string.IsNullOrWhiteSpace(p))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        var filtered = atoms
            .Where(a => !string.IsNullOrWhiteSpace(a.Content))
            .Select((a, idx) =>
            {
                var normalizedType = NormalizeRepurposeType(a.Type, extractAtoms);
                var platform = NormalizeRepurposePlatform(a.Platform);
                if (string.IsNullOrWhiteSpace(platform) || !requested.Contains(platform))
                {
                    platform = requested.FirstOrDefault() ?? "LinkedIn";
                }

                return new RepurposeAtomDto(
                    Id: $"rep-{DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()}-{idx + 1}",
                    Type: normalizedType,
                    Title: string.IsNullOrWhiteSpace(a.Title) ? null : a.Title.Trim(),
                    Content: a.Content!.Trim(),
                    Platform: platform,
                    SuggestedHashtags: NormalizeHashtags(a.SuggestedHashtags).Take(6).ToList(),
                    SuggestedCta: string.IsNullOrWhiteSpace(a.SuggestedCta) ? null : a.SuggestedCta.Trim()
                );
            })
            .ToList();

        if (extractAtoms)
        {
            var atomTypes = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "INSIGHT", "TIP", "QUOTE" };
            filtered = filtered.Where(f => atomTypes.Contains(f.Type)).ToList();
        }

        return filtered.Take(20).ToList();
    }

    private static string NormalizeRepurposePlatform(string? platform)
    {
        if (string.IsNullOrWhiteSpace(platform)) return string.Empty;
        var val = platform.Trim().ToLowerInvariant();

        return val switch
        {
            "linkedin" => "LinkedIn",
            "x" => "X",
            "twitter" => "X",
            "instagram" => "Instagram",
            "newsletter" => "Newsletter",
            "facebook" => "Facebook",
            _ => AllowedRepurposePlatforms.FirstOrDefault(p => p.Equals(platform.Trim(), StringComparison.OrdinalIgnoreCase)) ?? string.Empty
        };
    }

    private static string NormalizeRepurposeType(string? type, bool extractAtoms)
    {
        if (string.IsNullOrWhiteSpace(type))
        {
            return extractAtoms ? "INSIGHT" : "POST";
        }

        var upper = type.Trim().ToUpperInvariant();
        if (AllowedRepurposeTypes.Contains(upper, StringComparer.OrdinalIgnoreCase))
        {
            return upper;
        }

        return extractAtoms ? "INSIGHT" : "POST";
    }

    private sealed record GroqChatCompletionResponse(IReadOnlyCollection<GroqChoice>? Choices);
    private sealed record GroqChoice(GroqMessage? Message);
    private sealed record GroqMessage(string? Content);

    private sealed record IdeasEnvelope(IReadOnlyCollection<RawIdea>? Ideas);
    private sealed record RepurposeEnvelope(IReadOnlyCollection<RawRepurposeAtom>? Atoms);

    private sealed record RawIdea(
        string? Type,
        string? Hook,
        string? Title,
        string? Caption,
        IReadOnlyCollection<string>? Hashtags,
        IReadOnlyCollection<string>? Platforms,
        string? BestTime,
        string? EstimatedReach
    );

    private sealed record RawRepurposeAtom(
        string? Type,
        string? Title,
        string? Content,
        string? Platform,
        IReadOnlyCollection<string>? SuggestedHashtags,
        string? SuggestedCta
    );
}
